### ISSUE TITLE
Investigate member/method translations

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EFCore.SqlServer.DateOnlyTimeOnly#1]
Look at the NodaTime plugin (for hooking up translators + tests)

**DateOnly**

- [x] Methods: AddYears(), AddMonths(), AddDays()
- [x] Members: Year, Month, Day
- [x] DateDiff Year, Month, Day

**TimeOnly**
- [x] Methods: AddHours(), AddMinutes()
- [x] Members: Hour, Minute, Second, Millisecond

**Comment by ErikEJ** [comment]
@roji FYI

**Comment by roji** [comment]
Great! If you want, you can also contribute the built-in SQL Server provider support once SqlClient 5.1 is out - it's probably largely a copy-paste of your work here...
