### ISSUE TITLE
tostring method

### ISSUE THREAD

**Issue by ingreatsol** [ErikEJ/EFCore.SqlServer.DateOnlyTimeOnly#15]
DateOnly.toString() could not be translated. Additional information: Translation of method 'object.ToString' failed

**Comment by ErikEJ** [comment]
No sure it is possible. Can you please share some code?

**Comment by ingreatsol** [comment]
In this library there is some of that
https://github.com/josegerar/AspNetCoreDateAndTimeOnly/blob/master/src/Translators/MySqlServerObjectToStringTranslator.cs

**Comment by ErikEJ** [comment]
I  need you to share your code in a runnable way, and I will have a look.

**Comment by ErikEJ** [comment]
I implemented a fix for this in 7.0.5, please let me know if it solves your issue.
