### ISSUE TITLE
TimeOnly 24 hour clock

### ISSUE THREAD

**Issue by chtomek** [ErikEJ/EFCore.SqlServer.DateOnlyTimeOnly#2]
The SqlServerTimeOnlyTypeMapping.cs contains list of time formats, it uses hh as a format specifier which turns hours into 12hour clock. Dotnet TimeOnly type doesn't contain AM/PM marker and constructor takes 24 hour clock format value.
The array _timeFormats should contain HH as format specifier.
ATM it products incorrect mapping:
new TimeOnly(20, 0, 0) ==> '08:00:00'

**Comment by ErikEJ** [comment]
A PR ??

**Comment by ErikEJ** [comment]
I will look into it

**Comment by ErikEJ** [comment]
@chtomek I have released preview 3 on NuGet, thanks for reporting this

**Comment by chtomek** [comment]
@ErikEJ thank you appreciate. I have to get familiar with github process of contributing to projects. Next time (hopefully no need) will create PR.

**Comment by ErikEJ** [comment]
I appreciate your report. Important to get bugs fixed while in preview.
