### ISSUE TITLE
Add support for nullable types

### ISSUE THREAD

**Issue by mcetkovsky** [ErikEJ/EFCore.SqlServer.DateOnlyTimeOnly#20]
Nullable versions `DateOnly?` and `TimeOnly?` are still unmapped even after registering this extension via `UseDateOnlyTimeOnly()`.

`The 'DateOnly?' property '<model>' could not be mapped because the database provider does not support this type.`

**Comment by ErikEJ** [comment]
Could you provide some repro code?
