### ISSUE TITLE
Is this package fully merged to ef8?

### ISSUE THREAD

**Issue by DrkWzrd** [ErikEJ/EFCore.SqlServer.DateOnlyTimeOnly#21]
This package is a real deal, and right now in ef7 is always a must in my libraries.

The question is: will this package be needed in ef8 and future? will it have something more than the ef8 raw package?

**Comment by ErikEJ** [comment]
Thanks! This package will not be needed with EF Core 8, I will update the readme to make aware of that.

**Comment by ErikEJ** [comment]
Readme updated
